image:  repo.htl-md.schule:5003/gradle:8.2.1-jdk17-alpine

include:
  - project: onelitefeather/ci-template
    ref: Better-Pipelines
    file: s3-upload.yaml
  - project: onelitefeather/ci-template
    ref: Better-Pipelines
    file: sonarqube.yaml


variables:
  JAR_FILE: "Stardust.jar"
  BUCKET: "olf-dev"
  TEMPLATE: "default"