include:
  - project: onelitefeather/ci-template
    ref: Better-Pipelines
    file: s3-upload.yaml
  - project: onelitefeather/ci-template
    ref: Better-Pipelines
    file: sonarqube.yaml


variables:
  JAR_FILE: "Stardust.jar"
  BUCKET: "olf-dev"
  TEMPLATE: "default"

deploy:
  script:
    - gradle shadowJar