caffeine.jcache {
  stardust-user {
    policy.maximum.size = 2000
    policy.lazy-expiration.write = "300s"
  }
  stardust-user-naturalid {
    policy.maximum.size = 2000
    policy.lazy-expiration.write = "300s"
  }
  stardust-user-properties {
    policy.maximum.size = 10000
    policy.lazy-expiration.write = "300s"
  }
}